question_data = [
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                      "question": "The movie &quot;The Nightmare before Christmas&quot; was all done with physical objects.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Science: Gadgets", "type": "boolean", "difficulty": "easy",
                                      "question": "The communication protocol NFC stands for Near-Field Control.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "Gordon Freeman, the protagonist of &quot;Half-Life&quot;, is said to have once had a ponytail.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Geography", "type": "boolean", "difficulty": "easy",
                                      "question": "St. Louis is the capital of the US State Missouri.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
                                      "difficulty": "easy",
                                      "question": "In Pok&eacute;mon, Ash&#039;s Pikachu refuses to go into a pokeball.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "question": "When you cry in space, your tears stick to your face.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                      "question": "George Lucas directed the entire original Star Wars trilogy.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "The ghosts in &quot;Pac-Man&quot; and &quot;Ms. Pac-Man&quot; have completely different behavior.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "History", "type": "boolean", "difficulty": "easy",
                                      "question": "The French Kingdom helped the United States gain their independence over Great Britain during the Revolutionary War.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "question": "A pasodoble is a type of Italian pasta sauce.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]}
]
